### ISSUE TITLE
下载下来执行npm run dev报错，求助!!!

### ISSUE THREAD

**Issue by Leeehuixian** [armyja/mpvue-zanui#16]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mpvue-zanui@1.0.2 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mpvue-zanui@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\nodeJs\node_cache\_logs\2018-07-27T02_45_12_315Z-debug.log

**Comment by armyja** [comment]
尝试更换 node 和 npm 的版本。
$ node -v
v8.9.0

$ npm -v
5.6.0

**Comment by armyja** [comment]
git clone 最新版本
