### ISSUE TITLE
npm run dev 报错没绑定event？

### ISSUE THREAD

**Issue by breederComrade** [armyja/mpvue-zanui#19]
➜  mpvue-zanui git:(master) ✗ npm run dev

> mpvue-zanui@1.0.2 dev /Users/wangjun/code/github/wechat/mpvue-zanui
> node build/dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mpvue-zanui@1.0.2 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mpvue-zanui@1.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wangjun/.npm/_logs/2018-08-09T06_59_18_806Z-debug.log
![Uploading image.png…]()

**Comment by armyja** [comment]
git clone 最新版本
