### ISSUE TITLE
nom run dev 报错

### ISSUE THREAD

**Issue by VipMinF** [armyja/mpvue-zanui#6]
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1502:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mpvue-zanui@1.0.1 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mpvue-zanui@1.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wuweichang/.npm/_logs/2018-04-23T13_32_53_372Z-debug.log

**Comment by armyja** [comment]
请问执行 npm run dev 之前做了哪些操作呢？
